# -*- coding: utf-8 -*-
"""Fine-tune a Sentiment Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rGTn0tMay68KWopGDMZFkA4TJTanniUJ
"""

!pip install transformers datasets scikit-learn

from datasets import load_dataset

dataset = load_dataset("amazon_polarity")

small_data = dataset["train"].select(range(800))

data = []
labels = []

for i, item in enumerate(small_data):
    text = item["content"]
    original_label = item["label"]   # 0 or 1

    data.append(text)

    if original_label == 0:
        labels.append(0)   # Negative
    else:
        labels.append(1)   # Positive

from sklearn.model_selection import train_test_split

train_texts, test_texts, train_labels, test_labels = train_test_split(
    data, labels, test_size=0.2, random_state=42
)

from transformers import DistilBertTokenizer

tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")

train_encodings = tokenizer(train_texts, truncation=True, padding=True)
test_encodings = tokenizer(test_texts, truncation=True, padding=True)

import torch

class Dataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = Dataset(train_encodings, train_labels)
test_dataset = Dataset(test_encodings, test_labels)

from transformers import DistilBertForSequenceClassification

model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
)

from transformers import Trainer, TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=2,
    per_device_train_batch_size=8,
    logging_steps=10
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset
)

trainer.train()

from sklearn.metrics import accuracy_score, classification_report

predictions = trainer.predict(test_dataset)
preds = predictions.predictions.argmax(-1)

print("Accuracy:", accuracy_score(test_labels, preds))
print(classification_report(test_labels, preds))

texts = [
    "This phone is great",
    "Worst product ever",
    "It's okay, nothing special"
]

inputs = tokenizer(texts, return_tensors="pt", padding=True, truncation=True)
outputs = model(**inputs)

probs = torch.nn.functional.softmax(outputs.logits, dim=-1)
predictions = torch.argmax(probs, dim=1)

labels_map = {0:"Negative", 1:"Positive"}

for i in range(len(texts)):
    print(texts[i])
    print("Prediction:", labels_map[predictions[i].item()])
    print("Confidence:", probs[i].max().item())
    print()

